file_format: "1"
id: kiboard
name: KIBOARD 
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - kiboard_left
  - kiboard_right